### ISSUE TITLE
`SpawnEvent` has no new method

### ISSUE THREAD

**Issue by EmiOnGit** [janhohenheim/spew#1]
I thought I might as well checkout your new crate and see if I can provide a outside perspective :)

# The problem
I noticed that you use following snipped in your readme
```rust
fn setup_map(mut spawn_events: EventWriter<SpawnEvent<Object, Transform>>) {
    spawn_events.send(SpawnEvent::new(
        Objects::Player,
        Transform::from_xyz(0.0, 0.0, 0.0),
    ));
   // ...
}
```
but the `SpawnEvent` struct has no new function.

**Comment by janhohenheim** [comment]
Fixed in https://github.com/janhohenheim/spew/pull/4 :)
