### ISSUE TITLE
Documentation/Example Requests

### ISSUE THREAD

**Issue by zikes** [janhohenheim/spew#7]
I'd like to use this in a scenario where I would pass in more than one piece of information to the object being spawned. On top of `Transform` I might include the `Name`, for instance. I'm not sure of the best way to go about that, as `SpawnEvent` will only accept one field for data. Would it require creating a custom struct which combines all the data, such as `PlayerSpawnData` or `EnemySpawnData`?

Additionally, in the README you have a non-spew example involving a bullet being spawned, which makes use of `AssetServer`. I have situations where I need to access the asset server to load e.g. player/enemy sprites, however I'm not sure of the best way to go about that using spew. Would that be included as part of the custom spawn data (which I could see growing a bit overlong) or is there a more elegant solution?

**Comment by zikes** [comment]
I attempted a naive approach using a struct to pass collected data, but I'm running into an error which I'm not sure how to address. Here is the code for my attempt:

```rust
use bevy::prelude::*;
use spew::prelude::*;

#[derive(Debug, Eq, PartialEq)]
enum Object {
    Cube,
}

struct ObjectData {
    name: String,
    transform: Transform,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(SpewPlugin::<Object, ObjectData>::default())
        .add_spawners((Object::Cube, spawn_cube))
        .add_startup_system(spawn_the_cube)
        .run();
}

fn spawn_the_cube(mut spawn_events: EventWriter<SpawnEvent<Object, ObjectData>>) {
    spawn_events.send(SpawnEvent::with_data(
        Object::Cube,
        ObjectData {
            name: "the cube".to_owned(),
            transform: Transform::from_xyz(1., 2., 3.),
        },
    ));
}

fn spawn_cube(In(data): In<ObjectData>, mut commands: Commands) {
    info!("Spawning cube named {} at {}", data.name, data.transform.translation);
    commands.spawn((
        Name::new(data.name),
        data.transform,
    ));
}
```

And the error:
```sh
$ cargo run
   Compiling spew_test v0.1.0 (/home/zikes/Projects/rust/spew_test)
error[E0277]: the trait bound `Object: spew::spawner::Spawner<_>` is not satisfied
   --> src/main.rs:19:24
    |
19  |         .add_spawners((Object::Cube, spawn_cube))
    |          ------------  ^^^^^^^^^^^^ the trait `spew::spawner::Spawner<_>` is not implemented for `Object`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the trait `spew::spawner::Spawner<Marker>` is implemented for `(T, F)`
    = note: required for `(Object, for<'a, 'b> fn(bevy::prelude::In<ObjectData>, bevy::prelude::Commands<'a, 'b>) {spawn_cube})` to implement `spew::spawner::Spawners<(_, _)>`
note: required by a bound in `add_spawners`
   --> /home/zikes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spew-0.2.2/src/plugin.rs:146:12
    |
146 |         T: Spawners<D>;
    |            ^^^^^^^^^^^ required by this bound in `SpewApp::add_spawners`

error[E0277]: the trait bound `for<'a, 'b> fn(bevy::prelude::In<ObjectData>, bevy::prelude::Commands<'a, 'b>) {spawn_cube}: spew::spawner::Spawner<_>` is not satisfied
   --> src/main.rs:19:38
    |
19  |         .add_spawners((Object::Cube, spawn_cube))
    |          ------------                ^^^^^^^^^^ the trait `spew::spawner::Spawner<_>` is not implemented for fn item `for<'a, 'b> fn(bevy::prelude::In<ObjectData>, bevy::prelude::Commands<'a, 'b>) {spawn_cube}`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the trait `spew::spawner::Spawner<Marker>` is implemented for `(T, F)`
    = note: required for `(Object, for<'a, 'b> fn(bevy::prelude::In<ObjectData>, bevy::prelude::Commands<'a, 'b>) {spawn_cube})` to implement `spew::spawner::Spawners<(_, _)>`
note: required by a bound in `add_spawners`
   --> /home/zikes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spew-0.2.2/src/plugin.rs:146:12
    |
146 |         T: Spawners<D>;
    |            ^^^^^^^^^^^ required by this bound in `SpewApp::add_spawners`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `spew_test` (bin "spew_test") due to 2 previous errors
```

**Comment by mrkiffie** [comment]
Hi @zikes 

The error described above is because it is using the plural `add_spawners` instead of the singular `add_spawner`. 

- `add_spawner` takes a single tuple.
- `add_spawners` takes a tuple of tuples.

Changing to the singular `add_spawner` works as expected.

```diff
@@ -15,7 +15,7 @@ fn main() {
     App::new()
         .add_plugins(DefaultPlugins)
         .add_plugin(SpewPlugin::<Object, ObjectData>::default())
-        .add_spawners((Object::Cube, spawn_cube))
+        .add_spawner((Object::Cube, spawn_cube))
         .add_startup_system(spawn_the_cube)
         .run();
 }
```

Alternatively `add_spawners` can still be used by passing in a tuple of tuples.

```diff
@@ -15,7 +15,8 @@ fn main() {
     App::new()
         .add_plugins(DefaultPlugins)
         .add_plugin(SpewPlugin::<Object, ObjectData>::default())
-        .add_spawners((Object::Cube, spawn_cube))
+        .add_spawners(((Object::Cube, spawn_cube),))
+        //                                       ^ This comma causes it to be a tuple of 1 value.
         .add_startup_system(spawn_the_cube)
         .run();
 }
```

Hopefully this feedback allows you to continue exploring. 🙂

> Additionally, in the README you have a non-spew example involving a bullet being spawned, which makes use of `AssetServer`. I have situations where I need to access the asset server to load e.g. player/enemy sprites, however I'm not sure of the best way to go about that using spew. Would that be included as part of the custom spawn data (which I could see growing a bit overlong) or is there a more elegant solution?

Using the `spawn_cube` system as an example, it can get access to the `asset_server` by updating the system's function signature like normal systems.

```rust
fn spawn_cube(In(data): In<ObjectData>, mut commands: Commands, asset_server: Res<AssetServer>) {
    info!(
        "Spawning cube named {} at {}",
        data.name, data.transform.translation
    );

    commands.spawn((
        Name::new(data.name),
        SpriteBundle {
            texture: asset_server.load("texture.png"),
            transform: data.transform,
            ..default()
        },
    ));
}
```

I only discovered this crate today by reading through the [foxtrot game template](https://github.com/janhohenheim/foxtrot), perhaps it could be beneficial as a reference.

Unfortunately I can't offer any advise about what best practices might be at this stage.

**Comment by zikes** [comment]
@mrkiffie that resolves my issue perfectly, thank you very much!

**Comment by janhohenheim** [comment]
Exactly right, @mrkiffie, thanks for chiming in! 
@zikes you can also pass in a tuple if you want, i.e. `(String, Transform)` :)
As for best practices: I'd request all data that is not instance-specific from the ECS, like @mrkiffie showed. The `In` parameters can then be used for data that is exclusively needed by this instance, which are the name and position in this case.
